/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package okukushkina_java_2020_03;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    //new commit1
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
